### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by thapapadam** [infotechnab/Reservation#13]
![add new room2](https://cloud.githubusercontent.com/assets/10939157/6208667/4120d32c-b5e4-11e4-9549-521b0c428576.PNG)

**Comment by thapapadam** [comment]
![add new room2](https://cloud.githubusercontent.com/assets/10939157/6208677/6cc62388-b5e4-11e4-952c-883081c2d4cb.PNG)

**Comment by thapapadam** [comment]
![add new room 1](https://cloud.githubusercontent.com/assets/10939157/6208689/a9ad875a-b5e4-11e4-9309-53713c9d938b.PNG)

**Comment by bhomnath** [comment]
This was due to incomplete file update in server. Now the files are uptodate. So you can check it once again
