### ISSUE TITLE
delete button issue

### ISSUE THREAD

**Issue by crew0705** [infotechnab/Reservation#16]
Delete button shouldnot directly delete the contents.
Atleast there should be a warning saying "Are you sure you want to delete? "
Sometimes user may accidently click delete button.
![delete issue](https://cloud.githubusercontent.com/assets/10990988/6242954/66910a14-b760-11e4-94b5-a682b6c57abb.JPG)

**Comment by bhomnath** [comment]
For this case user can access deleted bookings and click on undo to reactivate the booking from the same pannel. So it is maintained in newer version.
