### ISSUE TITLE
email related 

### ISSUE THREAD

**Issue by thapapadam** [infotechnab/Reservation#3]
when we direct from gmail to delete or update  our booking it shows 404 error, i think it would be better to show procedure or something else to go on that action. otherwise it shouldnot be there.

**Comment by bhomnath** [comment]
Ok, now the delete as well as update buttons are with base url link only which will not redirect them to the home page of booking. This is under construction in local

**Comment by thapapadam** [comment]
dai delete wa update garda home page ma send garxa i think it should focus on above solution

**Comment by bhomnath** [comment]
Now the buttons are removed as it redirects to base url only.
