### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by crew0705** [infotechnab/Reservation#6]
![update error](https://cloud.githubusercontent.com/assets/10990988/6207998/d8ca69ec-b5d8-11e4-8732-991b5eceb51b.JPG)

**Comment by bhomnath** [comment]
This was due to unavailability of the image used in the given path. Now img tag is replaced with font icon thumb up in local.

**Comment by bhomnath** [comment]
Now it is updated on server. So please check it once again.
