### ISSUE TITLE
update

### ISSUE THREAD

**Issue by thapapadam** [infotechnab/Reservation#8]
![no update](https://cloud.githubusercontent.com/assets/10939157/6208043/83762322-b5d9-11e4-9d02-07ad739d6e9c.PNG)
dashboard > hotel>view all room>update info. we cannot update info unless we update images. and similar problem is in update issue case

**Comment by bhomnath** [comment]
Now It has been changed in local making image optional, if image is not selected to upload existing image will be shown and similarly if there image was not uploaded during addition of room, then also edit will not force to upload image.

**Comment by thapapadam** [comment]
now there is another proble in same case we get ans  "no files selected"

**Comment by bhomnath** [comment]
It is now updated in server. So please check it once
